[
    {
        "_id": "combos",
        "Açaí Puro": [],
        "Clássico": ['Banana', 'Leite em Pó', 'Leite Condensado', 'Granola'],
        "Doce Paixão": ['Morango', 'Bis', 'Leite Condensado', 'Disqueti'],
        "DuBom": ['Banana', 'Morango', 'Leite Condensado', 'Leite em Pó', 'Granola', 'Gotas de Chocolate', 'Granulado', 'Disqueti', 'Paçoca', 'Coco em Flocos', 'Raspas de Chocolate', 'Calde de Morango'],
        "Explosão": ['Banana', 'Sucrilhos', 'Leite em Pó', 'Mousse de Maracujá'],
        "Mix Tropical": ['Banana', 'Morango', 'Manga', 'Mel'],
        "Tentação": ['Mousse de Morango', 'Morango', 'Leite em Pó', 'Leite Condensado'],
        "Sonho de Valsa": ['Sonho de Valsa', 'Leite em Pó', 'Leite Condensado'],
        "KitKat": ['KitKat', 'Calda de Chocolate', 'Leite em Pó', 'Leite Condensado'],
        "Beijinho": ['Beijinho', 'Leite em Pó', 'Coco em Flocos'],
        "Brigadeiro": ['Brigadeiro', 'Mousse de Chocolate', 'Leite em Pó', 'Calda de Chocolate', 'Granulado'],
        "Chokito": ['Chokito', 'Calda de Caramelo', 'Paçoca', 'Leite em Pó', 'Sucrilhos'],
        "Prestigio": ['Prestígio', 'Power Ball', 'Leite Condensado', 'Coco em Flocos', 'Mousse de chocolate'],
        "Ouro Branco": ['Ouro Branco', 'Sucrilhos', 'Leite em Pó', 'Leite Consdensado', 'Calda de Morango'],
        "Oreo": ['Oreo', 'Raspas de Chocolate', 'Leite em Pó', 'Nescal Cereal', 'Calda de Chocolate'],
        "Trufado": ['Trufa de Chocolate', 'Coco em Flocos', 'Calda de Morango'],
        "Diamante Negro": ['Diamanter Negro', 'Leite Condensado', 'Leite em Pó', 'Ovomaltine', 'Calda de Chocolate'],
        "Baton": ['Baton', 'Power Ball', 'Leite em Pó', 'Leite Condensado', 'Calda de Chocolate'],
        "Laka": ['Laka', 'Raspas de Chocolate', 'Granola'],
        "Fit": ['Whey Protein', 'Banana', 'Aveia'],
        "Irresistível": ['Creme de Morango', 'Morango', 'Leite em Pó', 'Calda de Morango', 'Raspas de Chocolate'],
        "Liberdade": ['Mel', 'Leite em Pó', 'Leite Condensado', 'Granola', 'Calda de Morango'],
    },
    {
        "_id": "frutas",
        "Abacaxi": True,
        "Banana": True,
        "Coco em flocos": True,
        "Manga": True,
        "Morango": True
    },
    {
        "_id":  "derivados do leite",
        "Brigadeiro": True,
        "Leite condensado": True,
        "Nescau cereal": True,
        "Creme de morango": True,
        "Leite em pó": True,
        "Mousse de limão": True,
        "Mousse de maracujá": True,
        "Mousse de morango": True,
        "Mousse de chocolate": True,
        "Sorvete": True,
        "Beijinho": True
    },
    {
        "_id": "cereais",
        "Aveia": True,
        "Farinha láctea": True,
        "Granola": True,
        "Sucrilhos": True
    },
    {
        "_id": "chocolates",
        "Batom": True,
        "Disquete": True,
        "Kitkat": True,
        "Ovomaltine": True,
        "Diamante negro": True,
        "Gotas de chocolate": True,
        "Granulado": True,
        "Oreo": True,
        "Trufa de chocolate": True,
        "Ouro branco": True,
        "Raspas de chocolate": True,
        "Sonho de valsa": True,
        "Chokito": True,
        "Prestigio": True,
        "Bis": True,
        "Nutella": True,
        "Laka": True,
        "Power ball": True
    },
    {
        "_id": "diversos",
        "Mel": True,
        "Whey protein": True,
        "Paçoca": True
    },
    {
        "_id": "cobertutas",
        "Calda de Chocolate": True,
        "Calda de morango": True,
        "Calda de caramelo": True
    }
]
